### ISSUE TITLE
Error:java: error reading C:\Users\USER\.m2\repository\net\minecraft\minecraft\1.8.8\minecraft-1.8.8.jar; error in opening zip file

### ISSUE THREAD

**Issue by ghost** [DasDirt/MavenMCPInstaller#1]
Error:java: error reading C:\Users\USER\.m2\repository\net\minecraft\minecraft\1.8.8\minecraft-1.8.8.jar; error in opening zip file

**Comment by realdirt** [comment]
It looks like a Maven error. I don't know how exactly you can fix it automatically. However, you can download the missing library from here: [https://github.com/DasDirt/MCPMavenRepository/raw/repository/net/minecraft/minecraft/1.8.8/minecraft-1.8.8.jar](https://github.com/DasDirt/MCPMavenRepository/raw/repository/net/minecraft/minecraft/1.8.8/minecraft-1.8.8.jar) and manually put it in the folder.

**Comment by realdirt** [comment]
I just found out that I fucked up the pom.xml. I will fix it in the next few days

**Comment by realdirt** [comment]
Fixed (You need to reinstall mavenmcp the same way)
